# Generated by Django 6.0.3 on 2026-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("city_id", models.AutoField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "city",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "db_table": "country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField()),
                ("event_description", models.TextField(blank=True, null=True)),
                (
                    "event_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("finished", "Finished"),
                            ("postponed", "Postponed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "event",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                ("league_id", models.AutoField(primary_key=True, serialize=False)),
                ("league_name", models.CharField(max_length=150)),
                ("season", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "league",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                ("sport_id", models.AutoField(primary_key=True, serialize=False)),
                ("sport_name", models.CharField(max_length=100, unique=True)),
                ("sport_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sport",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=150)),
                ("short_name", models.CharField(blank=True, max_length=10, null=True)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "team",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("venue_id", models.AutoField(primary_key=True, serialize=False)),
                ("venue_name", models.CharField(max_length=150)),
                (
                    "venue_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("capacity", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "venue",
                "managed": False,
            },
        ),
    ]
