# Generated by Django 6.0.3 on 2026-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventResult",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("home_score", models.IntegerField()),
                ("away_score", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "event_result",
                "managed": False,
            },
        ),
    ]
